name: Build

on:
  workflow_call:
    inputs:
      tags:
        type: string
        description: The Docker Tags (see docker/metadata-action@v4 for available values)
        required: true

jobs:
  build-kubectl:
    runs-on: ubuntu-latest

    steps:
    - name: Build-kubetcl
      uses: coopTilleuls/action-docker-build-push@v10
      with:
        IMAGE_NAME: kubectl
        BUILD_CONTEXT: ./kubectl
        BUILD_TARGET: kubectl-mini
        REGISTRY_JSON_KEY: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_REPOSITORY: ghcr.io/cooptilleuls/sre/minimal/

    - name: Build-kubetcl-with-shell
      uses: coopTilleuls/action-docker-build-push@v10
      with:
        IMAGE_NAME: kubectl
        BUILD_CONTEXT: ./kubectl
        BUILD_TARGET: debian-kubectl
        REGISTRY_JSON_KEY: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_REPOSITORY: ghcr.io/cooptilleuls/sre



